### ISSUE TITLE
Yagasoft.Plugins.Common.RecurrenceExceptionHandler error 

### ISSUE THREAD

**Issue by mohamedsaad306** [os008/DynamicsCrm-BaseSolution#2]
hi Ahmed, 
i keep getting below error when i try to add user to team or remove user from team (Associate - Disassociate  ) . 
so i disabled the plugin steps till i figure the cause. 

Unhandled exception: 
Exception type: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]
Message: Retriable failure while executing plugin. This can be safely retried on a different host.Detail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>adfa2de1-d167-41e6-8fc0-e608260eb871</ActivityId>
  <ErrorCode>-2147220956</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiExceptionSourceKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">Plugin/Yagasoft.Plugins.Common.RecurrenceExceptionHandler, Yagasoft.Plugins.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=96f110ab5b32e2f5</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiOriginalExceptionKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">Microsoft.Crm.CrmException: Retriable failure while executing plugin. This can be safely retried on a different host. ---&gt; Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePluginRetriableException: Retriable failure while executing plugin. This can be safely retried on a different host.
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.&lt;&gt;c__DisplayClass26_0.&lt;Execute&gt;b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.CDSExecute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Extensibility.V5PluginProxyStep.ExecuteInternal(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.VersionedPluginProxyStepBase.Execute(PipelineExecutionContext context)
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Extensibility.VersionedPluginProxyStepBase.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.PipelineInstrumentationHelper.Execute(Boolean instrumentationEnabled, String stopwatchName, ExecuteWithInstrumentation action, PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.Pipeline.&lt;&gt;c__DisplayClass3_0.&lt;RunStep&gt;b__0()</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiStepKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">78358253-e98a-e611-9c0b-f8b156a3e077</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiDepthKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">1</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiActivityIdKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">adfa2de1-d167-41e6-8fc0-e608260eb871</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiPluginSolutionNameKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">YSCommonSolution</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiStepSolutionNameKey</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">YSCommonSolution</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiExceptionCategory</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">ClientError</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiExceptionMesageName</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">IsvUnExpected</d2p1:value>
    </KeyValuePairOfstringanyType>
    <KeyValuePairOfstringanyType>
      <d2p1:key>ApiExceptionHttpStatusCode</d2p1:key>
      <d2p1:value xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string">400</d2p1:value>
    </KeyValuePairOfstringanyType>
  </ErrorDetails>
  <HelpLink>http://go.microsoft.com/fwlink/?LinkID=398563&amp;error=Microsoft.Crm.CrmException%3a80040224&amp;client=platform</HelpLink>
  <Message>Retriable failure while executing plugin. This can be safely retried on a different host.</Message>
  <Timestamp>2023-08-21T04:27:00.4700522Z</Timestamp>
  <ExceptionRetriable>false</ExceptionRetriable>
  <ExceptionSource i:nil="true" />
  <InnerFault i:nil="true" />
  <OriginalException i:nil="true" />
  <TraceText>

[Yagasoft.Plugins.Common: Yagasoft.Plugins.Common.RecurrenceExceptionHandler]
[78358253-e98a-e611-9c0b-f8b156a3e077: Yagasoft.Plugins.Common.RecurrenceExceptionHandler: Associate of any entity]
Entered Microsoft.Dynamics.Sales.Plugins.PreOperationProductSalesLiteratureAssociate.Execute(), Correlation Id: 4bcd2514-cb11-4543-97ff-d2bee4fca6cc, Initiating User: fa77df14-4bd1-ed11-915d-00505697ddbe
Exiting Microsoft.Dynamics.Sales.Plugins.PreOperationProductSalesLiteratureAssociate.Execute(), Correlation Id: 4bcd2514-cb11-4543-97ff-d2bee4fca6cc, Initiating User: fa77df14-4bd1-ed11-915d-00505697ddbe
Entered Microsoft.Dynamics.Service.Plugins.PreOperationAssociate.Execute(), Correlation Id: 4bcd2514-cb11-4543-97ff-d2bee4fca6cc, Initiating User: fa77df14-4bd1-ed11-915d-00505697ddbe
Exiting Microsoft.Dynamics.Service.Plugins.PreOperationAssociate.Execute(), Correlation Id: 4bcd2514-cb11-4543-97ff-d2bee4fca6cc, Initiating User: fa77df14-4bd1-ed11-915d-00505697ddbe
Entered Microsoft.Dynamics.Sales.Plugins.PostOperationOpportunityAssociate.Execute(), Correlation Id: 4bcd2514-cb11-4543-97ff-d2bee4fca6cc, Initiating User: fa77df14-4bd1-ed11-915d-00505697ddbe
Exiting Microsoft.Dynamics.Sales.Plugins.PostOperationOpportunityAssociate.Execute(), Correlation Id: 4bcd2514-cb11-4543-97ff-d2bee4fca6cc, Initiating User: fa77df14-4bd1-ed11-915d-00505697ddbe
Entered PluginContext, Correlation Id: 4bcd2514-cb11-4543-97ff-d2bee4fca6cc, Initiating User: fa77df14-4bd1-ed11-915d-00505697ddbe
Validation completed
Entered PluginContext, Correlation Id: 4bcd2514-cb11-4543-97ff-d2bee4fca6cc, Initiating User: fa77df14-4bd1-ed11-915d-00505697ddbe
Validation completed

</TraceText>
</OrganizationServiceFault>

**Comment by yagasoft** [comment]
Hello, @mohamedsaad306,
Thank you for reporting the issue.
I will test it locally.
